// ---------------------------------------------------------------------------
// The shared Open Graph card.
//
// Next does NOT deep-merge metadata: a page that exports its own `openGraph`
// replaces the parent's object entirely rather than inheriting its `images`.
// So declaring the card once in app/layout.tsx puts it on the homepage and
// nowhere else — every page with a title of its own silently loses it.
//
// Every page that sets openGraph or twitter therefore has to spread these in
// by hand. If a new page is added with its own metadata, it needs these two
// lines or its shares go back to a blank grey box.
//
// The image itself is generated by scripts/render-og-image.ts.
// ---------------------------------------------------------------------------

export const OG_IMAGE = {
  url: '/images/og-default.png',
  width: 1200,
  height: 630,
  alt: 'Mountain Studios — see your website before you pay for it',
}

/** Spread into `openGraph`. */
export const OG_IMAGES = [OG_IMAGE]

/** Spread into `twitter`. */
export const TWITTER_IMAGES = [OG_IMAGE.url]
